src/inol_rest/api/models.py
from inol_rest.api import api
from flask_restplus import fields

# Models

training_option = api.model('training_option', {   
                               "scheme": fields.String(description='Training schema set x reps @ intensity'),
                               "exercise_inol": fields.Float(description='The total exercise inol'),
                               "set_inol": fields.Float(description='The set inol'),
                               "volume": fields.Integer(description='Total volume'),
                               "weight": fields.Float(description='Weight (exact)'),
                               "weight_powerlifting": fields.Float(description='Weight (rounded to 2.5kg)'),
                               "weight_olympic": fields.Float(description='Weight (rounded to 1kg)')
                            }
                           )



training_session = api.model('training_session',
                           {   
                               "week": fields.Integer(description='Training week'),
                               "intensity": fields.Float(description='The training intensity'),
                               "target_exercise_inol": fields.Float(description='The target exercise inol')
                            }
                           )

training_model = api.model('training_model',
                           {   
                               "training_sessions": fields.List(fields.Nested(training_session), description='Training sessions which make up the overall model'),
                            }
                           )
# Models Request

inol_request = api.model('inol_request', {
    'reps': fields.Integer(required=True, description='The number of reps in the set'),
    'weight': fields.Float(required=True, description='The number weight of the set'),
    'maximum': fields.Float(required=True, description='Current one rep max')
})

training_options_request = api.model('training_options_request', {
    # current_max, max_reps, intensity, min_sets, max_sets, min_set_inol, max_set_inol, min_exercise_inol, max_exercise_inol
    'intensity': fields.Float(required=True, description='The training intensity to generate options for. e.g 80%'),
    'maximum': fields.Float(required=True, description='Current one rep max'),
    'max_reps': fields.Integer(required=True, description='The maximum number of reps per set.'),
    'max_sets': fields.Integer(required=True, description='The maximum number of sets'),
    'min_set_inol': fields.Float(required=True, description='The minimum set inol to consider'),
    'max_set_inol': fields.Float(required=True, description='The maximum set inol to consider'),
    'min_exercise_inol': fields.Float(required=True, description='The minimum exercise inol to consider'),
    'max_exercise_inol': fields.Float(required=True, description='The minimum exercise inol to consider')
})



training_plan_request = api.model('training_plan_request', {
    # current_max, max_reps, intensity, min_sets, max_sets, min_set_inol, max_set_inol, min_exercise_inol, max_exercise_inol
    'name': fields.String(required=True, description='Exercise name e.g bench'),
    'maximum': fields.Float(required=True, description='Current one rep max'),
    'max_reps': fields.Integer(required=True, description='The maximum number of reps per set.'),
    'max_sets': fields.Integer(required=True, description='The maximum number of sets'),
    'min_set_inol': fields.Float(required=True, description='The minimum set inol to consider'),
    'max_set_inol': fields.Float(required=True, description='The maximum set inol to consider'),
    'min_exercise_inol': fields.Float(required=True, description='The minimum exercise inol to consider'),
    'max_exercise_inol': fields.Float(required=True, description='The minimum exercise inol to consider'),
    'training_model' : fields.Nested(training_model, required=True,description='The training model')
})

# Models Responses

inol_response = api.model('inol_response', {
    'reps': fields.Integer(required=True, description='The number of reps in the set'),
    'weight': fields.Float(required=True, description='The number weight of the set'),
    'maximum': fields.Float(required=True, description='Current one rep max'),
    'inol': fields.Float(description='The inol of the set'),
    'tracking_id': fields.String(required=True, description="Tracking id")
})



training_options_response = api.model('training_options_response', {
    'intensity': fields.Float(required=True, description='The training intensity to generate options for. e.g 80%'),
    'maximum': fields.Float(required=True, description='Current one rep max'),
    'max_reps': fields.Integer(required=True, description='The maximum number of reps per set.'),
    'max_sets': fields.Integer(required=True, description='The maximum number of sets'),
    'min_set_inol': fields.Float(required=True, description='The minimum set inol to consider'),
    'max_set_inol': fields.Float(required=True, description='The maximum set inol to consider'),
    'min_exercise_inol': fields.Float(required=True, description='The minimum exercise inol to consider'),
    'max_exercise_inol': fields.Float(required=True, description='The minimum exercise inol to consider'),
    'training_options': fields.List(fields.Nested(training_option), description='The training options'),
    'tracking_id': fields.String(required=True, description="Tracking id")
})

training_plan_response = api.model('training_plan_response', {
    'name': fields.String(required=True, description='Exercise name e.g bench'),
    'maximum': fields.Float(required=True, description='Current one rep max'),
    'max_reps': fields.Integer(required=True, description='The maximum number of reps per set.'),
    'max_sets': fields.Integer(required=True, description='The maximum number of sets'),
    'min_set_inol': fields.Float(required=True, description='The minimum set inol to consider'),
    'max_set_inol': fields.Float(required=True, description='The maximum set inol to consider'),
    'min_exercise_inol': fields.Float(required=True, description='The minimum exercise inol to consider'),
    'max_exercise_inol': fields.Float(required=True, description='The minimum exercise inol to consider'),
    'training_plan': fields.List(fields.Nested(training_option), description='The training options'),
    'tracking_id': fields.String(required=True, description="Tracking id")
})

src/inol_rest/__init__.py
from flask import Flask
from flask_debugtoolbar import DebugToolbarExtension
#from flask_restplus import Api
import logging
from logging.handlers import RotatingFileHandler
from logging import FileHandler
import os
from os.path import expanduser
import yaml
#from cloghandler import ConcurrentRotatingFileHandler

from flask_zipkin import Zipkin

#zipkin = Zipkin(sample_rate=10)


from .config import config_by_name
import sys

toolbar = DebugToolbarExtension()

#api = Api()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_by_name[config_name])
    
    #init debug toolbar
    toolbar.init_app(app)
    #init api restplus
    #api.init_app(app)

    #zipkin.init_app(app)

    from inol_rest.home import home as home_blueprint
    app.register_blueprint(home_blueprint, url_prefix='/')

    from inol_rest.api import api_blueprint as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api')

    #setup logging
    
    if os.getenv("INOL_REST_DEBUG", None) is not None:
        __setup_logging(default_level=logging.DEBUG)
    else:
        __setup_logging()
    
    #handler = FileHandler('C:/var/tmp/flask.log', mode='w')
    #handler.setLevel(logging.INFO)
    #app.logger.addHandler(handler)


    return app


 
def __setup_logging(default_level=logging.FATAL):
    """
    Setup logging configuration
    #https://docs.python.org/2/library/logging.config.html#logging-config-dictschema
    """
    #print default_level
    default_format = "%(asctime)s - %(levelname)s - %(name)s - %(module)s.%(funcName)s: %(message)s"
    
    home_dir = expanduser("~")
    
    logging_config = os.getenv("INOL_REST_LOG_YAML", '{0}/logging.yaml'.format(home_dir))
    
    
    if os.path.exists(logging_config):
        #try as if logging_config is an absolute path
        with open(logging_config, 'rt') as f:
            config = yaml.safe_load(f.read())
            logging.config.dictConfig(config)
    else:
        #print "WARN: could not find {0}".format(logging_config)
        #log to stderr. This works better with ansible
        logging.basicConfig(level=default_level, format=default_format,stream=sys.stderr)
        
    logger = logging.getLogger( __name__ )
    logger.debug("logging init complete")

src/inol_rest/api/__init__.py
from flask import Blueprint
from flask_restplus import Api
from flask_restplus import Resource
from flask_restplus import fields
from werkzeug.local import LocalProxy
from flask import current_app
from inol_rest.inol_calc.calculator import calculate_set_inol
import uuid
import math


logger = LocalProxy(lambda: current_app.logger)


api_blueprint = Blueprint('api', __name__)
api = Api(api_blueprint, version='1.0', title='INOL Rest API',
    description='REST Service for INOL (Intensity x Number Of Lifts)',
)

#this has to come after the api is defined as we have a circular reference. As painful as this is, its cleaner than having everything in one file.
#from inol_rest.api.models import inolResponse, inolRequest, trainingModel, trainingOption, trainingOptionsRequest, trainingOptionsResponse, trainingPlanRequest, trainingPlanResponse, trainingSession

from inol_rest.api.views import calc, training

src/inol_rest/api/views.py
import uuid

from flask_restplus import Resource

from inol_rest.api import api
from inol_rest.api import logger
from inol_rest.api.models import inol_response, inol_request, training_model, training_option, training_options_request, training_options_response, training_plan_request, training_plan_response, training_session
from inol_rest.api.core import calculate_set_inol_weight, generate_training_options, generate_training_plan

calc = api.namespace('calc', description='calculators')
training = api.namespace('training', description='training operations')





@calc.route('/inol')
@api.doc()
class Inol(Resource):

    @api.marshal_with(inol_response)
    @api.expect(inol_request, validate=True)
    @api.response(200, 'Success', inol_response)
    def post(self):

        tracking_id = uuid.uuid4()
        
        logger.info("{0} payload {1}".format(tracking_id, api.payload))

        # inboundRequest
        i = api.payload
        
        i['inol'] = calculate_set_inol_weight(i['reps'], i['weight'], i['maximum'])
        i['tracking_id'] = tracking_id
        
        # inol_response = inol_response(reps=data.reps)
        return i


# Test message
# {
#   "min_set_inol": 0.05,
#   "intensity": 80,
#   "min_exercise_inol": 0.3,
#   "max_exercise_inol": 2,
#   "maximum": 182.5,
#   "max_sets": 6,
#   "max_reps": 12,
#   "max_set_inol": 0.5
# }

#curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "min_set_inol": 0.05, "intensity": 80, "min_exercise_inol": 0.3, "max_exercise_inol": 2, "maximum": 182.5, "max_sets": 6, "max_reps": 12, "max_set_inol": 0.5 }' 'http://walandre9:5000/api/training/options'







@training.route('/options')
@api.doc()
class training_options(Resource):

    @api.marshal_with(training_options_response)
    @api.expect(training_options_request, validate=True)
    @api.response(200, 'Success', training_options_response)
    def post(self):

        tracking_id = uuid.uuid4()
        
        logger.info("{0} payload {1}".format(tracking_id, api.payload))

        # inboundRequest
        i = api.payload
        # current_max, max_reps, intensity,  max_sets, min_set_inol, max_set_inol, min_exercise_inol, max_exercise_inol
        training_options = generate_training_options(
            i['intensity'],
            i['maximum'],
            i['max_reps'],
            i['max_sets'],
            i['min_set_inol'],
            i['max_set_inol'],
            i['min_exercise_inol'],
            i['max_exercise_inol'])
        i['training_options'] = training_options
        i['tracking_id'] = tracking_id
        
        return i





# {
#     "training_model": {
#         "training_sessions": [
#             {
#                 "week": 1,
#                 "intensity": 65,
#                 "target_exercise_inol": 0.8
#             }, {
#                 "week": 2,
#                 "intensity": 70,
#                 "target_exercise_inol": 0.9
#             }, {
#                 "week": 3,
#                 "intensity": 75,
#                 "target_exercise_inol": 1.0
#             }, {
#                 "week": 4,
#                 "intensity": 80,
#                 "target_exercise_inol": 0.8
#             }, {
#                 "week": 5,
#                 "intensity": 85,
#                 "target_exercise_inol": 0.9
#             }, {
#                 "week": 6,
#                 "intensity": 90,
#                 "target_exercise_inol": 1.0
#             }, {
#                 "week": 7,
#                 "intensity": 95,
#                 "target_exercise_inol": 0.8
#             }
#         ]
#     },
#     "name": "bench",
#     "max": 182.5,
#     "max_sets": 6,
#     "max_reps": 12,
#     "min_exercise_inol": 0.3,
#     "max_exercise_inol": 2,
#     "min_set_inol": 0.05,
#     "max_set_inol": 0.5
# }


# curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
#      "training_model": { \ 
#          "training_sessions": [ \ 
#              { \ 
#                  "week": 1, \ 
#                  "intensity": 65, \ 
#                  "target_exercise_inol": 0.8 \ 
#              }, { \ 
#                  "week": 2, \ 
#                  "intensity": 70, \ 
#                  "target_exercise_inol": 0.9 \ 
#              }, { \ 
#                  "week": 3, \ 
#                  "intensity": 75, \ 
#                  "target_exercise_inol": 1.0 \ 
#              }, { \ 
#                  "week": 4, \ 
#                  "intensity": 80, \ 
#                  "target_exercise_inol": 0.8 \ 
#              }, { \ 
#                  "week": 5, \ 
#                  "intensity": 85, \ 
#                  "target_exercise_inol": 0.9 \ 
#              }, { \ 
#                  "week": 6, \ 
#                  "intensity": 90, \ 
#                  "target_exercise_inol": 1.0 \ 
#              }, { \ 
#                  "week": 7, \ 
#                  "intensity": 95, \ 
#                  "target_exercise_inol": 0.8 \ 
#              } \ 
#          ] \ 
#      }, \ 
#      "name": "bench", \ 
#      "max": 182.5, \ 
#      "max_sets": 6, \ 
#      "max_reps": 12, \ 
#      "min_exercise_inol": 0.3, \ 
#      "max_exercise_inol": 2, \ 
#      "min_set_inol": 0.05, \ 
#      "max_set_inol": 0.5 \ 
#  }' 'http://walandre9:5000/api/training/plan'

@training.route('/plan')
@api.doc()
class TrainingPlan(Resource):

    @api.marshal_with(training_plan_response)
    @api.expect(training_plan_request, validate=True)
    @api.response(200, 'Success', training_plan_response)
    def post(self):

        tracking_id = uuid.uuid4()
        
        logger.info("{0} payload {1}".format(tracking_id, api.payload))

        # inboundRequest
        i = api.payload
        
        training_plan = generate_training_plan(
            
            #name, maximum, max_reps, max_sets, min_set_inol, max_set_inol, min_exercise_inol, max_exercise_inol, training_model
            i['name'],
            i['maximum'],
            i['max_reps'],
            i['max_sets'],
            i['min_set_inol'],
            i['max_set_inol'],
            i['min_exercise_inol'],
            i['max_exercise_inol'],
            i['training_model']
            )
        
        
        i['training_plan'] = training_plan
        i['tracking_id'] = tracking_id
        
        return i

src/inol_rest/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from inol_rest.home import views

src/inol_rest/home/views.py
from flask import render_template
from flask import current_app

from inol_rest.home import home
import datetime

@home.app_errorhandler(403)
def forbidden(e):
    return render_template('403.html'), 403


@home.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@home.app_errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500


def base_properties():
    base = {}
    
    year = datetime.datetime.now().year
    application_domain_name = current_app.config['APPLICATION_DOMAIN_NAME']
    application_name = current_app.config['APPLICATION_NAME']
    google_analytics_tracking_id = current_app.config['GOOGLE_ANALYTICS_TRACKING_ID']
    
    base['year'] = year
    base['application_domain_name'] = application_domain_name
    base['application_name'] = application_name
    base['google_analytics_tracking_id'] = google_analytics_tracking_id

    
    return base
    


@home.route('/')
def index():
    #base = base_properties()
    
    
    return render_template('index.html', base_properties=base_properties())



@home.route('inol')
def inol():
    
    return render_template('inol.html', base_properties=base_properties())



@home.route('plan')
def plan():
    
    return render_template('plan.html', base_properties=base_properties())

src/inol_rest/templates/old/base.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js full" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1">  -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/docs.css')}}">
<!--         <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-theme.min.css')}}"> -->
         <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css')}}">
        <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/cover.css')}}"> -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css')}}">


        <script	src="{{ url_for('static', filename='js/vendor/modernizr-2.8.3-respond-1.4.2.min.js') }}"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
 
 
 	<!-- Navigation -->
	<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">



		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="index.html">Training</a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse"
				id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{{ url_for('home.inol') }}">Inol</a></li>
					
					<li><a href="about.html">About</a></li>
					<li><a href="calculators.html">Calculators</a></li>
					<li><a href="log.html">Log</a></li>
					<li><a class="fb-login-button" data-max-rows="1"
						data-size="large" data-show-faces="false"
						data-auto-logout-link="true" onlogin="facebookLoginHandler();"
						data-scope="basic_info,public_profile,email"></a></li>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container -->
	</nav>

	<!-- Page Content -->
	<div class="container">

		{% block content %} {% endblock %}

	</div>

 
	<!-- /container -->        
    
    	<script	src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="{{ url_for('static', filename='js/vendor/jquery-1.11.2.min.js')}}"><\/script>')</script>
    
		<script	src="{{ url_for('static', filename='js/vendor/bootstrap.min.js') }}"></script>


        <script src="{{ url_for('static', filename='js/base.js') }}"></script>

		{% block scripts %} {% endblock %}

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','{{ base_properties.google_analytics_tracking_id}}','auto');ga('send','pageview');
        </script>
    </body>
</html>

src/inol_rest/templates/old/index.html
{% extends "base.html" %} {% block content %}


     <div class="jumbotron">
        <h1>Training</h1>
        <p class="lead">Generate your own sensible training programs that will not destroy you.</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
      </div>




{% endblock %}

{% block scripts %} 

<script src="{{ url_for('static', filename='js/index.js') }}"></script>

{% endblock %}

src/inol_rest/templates/old/index2.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-theme.min.css')}}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">


        <script	src="{{ url_for('static', filename='js/vendor/modernizr-2.8.3-respond-1.4.2.min.js') }}"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Company 2015</p>
      </footer>
    </div>
	<!-- /container -->        
    
    	<script	src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="{{ url_for('static', filename='js/vendor/jquery-1.11.2.min.js')}}"><\/script>')</script>
    
		<script	src="{{ url_for('static', filename='js/vendor/bootstrap.min.js') }}"></script>


        <script src="{{ url_for('static', filename='js/main.js') }}"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>